on: [push, pull_request]

name: Continuous Integration

env:
  CARGO_TERM_COLOR: always

jobs:
  build_x86_64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get submodules
      run: git submodule init & git submodule update
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  build_thumbv7m-none-eabi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install target
      run: rustup target add thumbv7m-none-eabi
    - name: Get submodules
      run: git submodule init & git submodule update
    - name: Build
      run: cargo build --verbose

  build_thumbv7em-none-eabihf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install target
      run: rustup target add thumbv7em-none-eabihf
    - name: Get submodules
      run: git submodule init & git submodule update
    - name: Build
      run: cargo build --verbose
